### ISSUE TITLE
Отступ перед результатом

### ISSUE THREAD

**Issue by coursar** [AnastasiaBezb/07_homework_wallpaper#1]
Поставьте вертикальный отступ перед выводом результата, чтобы он не прилипал к форме:

![Screenshot from 2019-04-01 20-06-46](https://user-images.githubusercontent.com/3601892/55345887-b4c4f380-54b9-11e9-9ce8-a6e9f4b430c5.png)

**Comment by coursar** [comment]
Если закрываете issue commit'ом, то старайтесь не включать в этот коммит того, что не относится к issue

**Comment by AnastasiaBezb** [comment]
хорошо
